"""服务器配置生成与读写。

负责生成 Minecraft server.properties、Geyser config.yml、Floodgate config.yml，
同意 EULA，以及从已有 server.properties 读回配置。
纯标准库实现，路径全部使用 pathlib。
"""
from __future__ import annotations

from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Dict

from . import constants as C


@dataclass
class ServerConfig:
    """互通服务器配置。"""

    server_dir: Path
    java_port: int = C.JAVA_DEFAULT_PORT
    bedrock_port: int = C.BEDROCK_DEFAULT_PORT
    online_mode: bool = True          # 正版验证
    floodgate_enabled: bool = True     # 允许基岩版离线加入
    xms: str = C.DEFAULT_XMS
    xmx: str = C.DEFAULT_XMX
    difficulty: str = "normal"         # peaceful/easy/normal/hard
    gamemode: str = "survival"        # survival/creative/adventure/spectator
    motd: str = "MC Bridge Server"
    max_players: int = 20
    whitelist: bool = False
    level_name: str = "world"
    view_distance: int = 10

    # ---- 便捷路径 ----
    @property
    def properties_path(self) -> Path:
        return self.server_dir / C.SERVER_PROPERTIES

    @property
    def geyser_config_path(self) -> Path:
        return self.server_dir / C.GEYSER_CONFIG_DIR / "config.yml"

    @property
    def floodgate_config_path(self) -> Path:
        return self.server_dir / C.FLOODGATE_CONFIG_DIR / "config.yml"


def _b(v: bool) -> str:
    return "true" if v else "false"


def generate_server_properties(cfg: ServerConfig, dest: Path) -> Path:
    """生成 server.properties，返回写入路径。"""
    dest.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "#Minecraft server properties",
        "# Generated by MC Bridge Tool",
        "server-ip=",
        f"server-port={int(cfg.java_port)}",
        f"online-mode={_b(cfg.online_mode)}",
        f"difficulty={cfg.difficulty}",
        f"gamemode={cfg.gamemode}",
        f"hardcore=false",
        f"motd={cfg.motd}",
        f"max-players={int(cfg.max_players)}",
        f"white-list={_b(cfg.whitelist)}",
        f"enforce-whitelist={_b(cfg.whitelist)}",
        f"level-name={cfg.level_name}",
        f"level-seed=",
        f"level-type=minecraft\\:normal",
        f"view-distance={int(cfg.view_distance)}",
        f"simulation-distance=10",
        f"pvp=true",
        f"enable-query=false",
        f"enable-rcon=false",
        f"allow-flight=false",
        f"spawn-protection=0",
        f"enable-status=true",
        "",
    ]
    dest.write_text("\n".join(lines), encoding="utf-8")
    return dest


def generate_geyser_config(cfg: ServerConfig, dest: Path) -> Path:
    """生成 Geyser-Spigot 的 config.yml。"""
    dest.parent.mkdir(parents=True, exist_ok=True)
    auth_type = "floodgate" if cfg.floodgate_enabled else "online"
    text = (
        "# Generated by MC Bridge Tool\n"
        "config-version: 3\n"
        "bedrock:\n"
        "  address: 0.0.0.0\n"
        f"  port: {int(cfg.bedrock_port)}\n"
        "  clone-remote-port: false\n"
        "  proxy-protocol: false\n"
        "  motd1: 'MC Bridge Server'\n"
        "  motd2: 'Geyser Edition'\n"
        f"  server-name: '{cfg.motd}'\n"
        "remote:\n"
        "  address: auto\n"
        f"  port: {int(cfg.java_port)}\n"
        f"  auth-type: {auth_type}\n"
        "  use-proxy-protocol: false\n"
        "floodgate-key-file: key.pem\n"
        "saved-login-data:\n"
        "  auto-saving: true\n"
        "ping-passthrough: true\n"
        "debug-mode:\n"
        "  log-packet-translations: false\n"
        "\n"
    )
    dest.write_text(text, encoding="utf-8")
    return dest


def generate_floodgate_config(cfg: ServerConfig, dest: Path) -> Path:
    """生成 floodgate 的 config.yml。"""
    dest.parent.mkdir(parents=True, exist_ok=True)
    text = (
        "# Generated by MC Bridge Tool\n"
        "key-file-name: key.pem\n"
        "username-prefix: '.'\n"
        "disallow-linking-accounts: false\n"
        "config-version: 2\n"
        "online-mode:\n"
        "  allow-floodgate-clients: true\n"
        "  allow-only-linkedAccounts: false\n"
        "\n"
    )
    dest.write_text(text, encoding="utf-8")
    return dest


def accept_eula(server_dir: Path) -> Path:
    """写入 eula.txt=eula=true，返回路径。"""
    server_dir.mkdir(parents=True, exist_ok=True)
    p = server_dir / C.EULA_FILE
    p.write_text("#Generated by MC Bridge Tool\n"
                 "eula=true\n", encoding="utf-8")
    return p


def _parse_properties(text: str) -> Dict[str, str]:
    out: Dict[str, str] = {}
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" in line:
            k, v = line.split("=", 1)
            out[k.strip()] = v.strip()
    return out


def _to_int(v: str, default: int) -> int:
    try:
        return int(v)
    except (TypeError, ValueError):
        return default


def _to_bool(v: str, default: bool = False) -> bool:
    return str(v).strip().lower() == "true" if v is not None else default


def load_config(server_dir: Path) -> ServerConfig:
    """从已有 server.properties 读回配置；缺失字段用默认值。"""
    cfg = ServerConfig(server_dir=Path(server_dir))
    p = server_dir / C.SERVER_PROPERTIES
    if p.exists():
        data = _parse_properties(p.read_text(encoding="utf-8", errors="ignore"))
        cfg.java_port = _to_int(data.get("server-port", ""), C.JAVA_DEFAULT_PORT)
        cfg.online_mode = _to_bool(data.get("online-mode", "true"), True)
        cfg.difficulty = data.get("difficulty", "normal")
        cfg.gamemode = data.get("gamemode", "survival")
        cfg.motd = data.get("motd", "MC Bridge Server")
        cfg.max_players = _to_int(data.get("max-players", ""), 20)
        cfg.whitelist = _to_bool(data.get("white-list", "false"), False)
        cfg.level_name = data.get("level-name", "world")
        cfg.view_distance = _to_int(data.get("view-distance", ""), 10)
    # 基岩端口 / JVM 内存等 server.properties 不记录，保持默认。
    return cfg


def save_config(cfg: ServerConfig) -> None:
    """写回全部配置文件：server.properties、geyser/floodgate config.yml、eula。"""
    cfg.server_dir.mkdir(parents=True, exist_ok=True)
    generate_server_properties(cfg, cfg.properties_path)
    generate_geyser_config(cfg, cfg.geyser_config_path)
    generate_floodgate_config(cfg, cfg.floodgate_config_path)
    accept_eula(cfg.server_dir)
